
{
    'name': 'Sanitairkamer Install ',
    'version': '1.0',
    'description': """
    Sanitairkamer - All modules that need to be installed.
==================
        """,
    'website': 'www.erpopen.nl',
    'category': '',
    'author': 'Thom Peele, ERP|OPEN',
    'depends': [
        'account',
        'sale',
        'stock',
        'purchase',
        'business_2_business',
        'erpopen_magento_odoo',
        'crm',
        'stock',
        'mrp',
        'sale',
        'stock_account',
        'mail',
        'account',
        'account_accountant',
        'website',
        'mrp_workorder',
        'website_sale',
        'purchase',
        'account_bank_statement_import',
        'account_bank_statement_import_ofx',
        'account_extension',
        'account_reports',
        'analytic',
        'auth_crypt',
        'auth_signup',
        'b2b_magento_supplier',
        'barcodes',
        'base',
        'base_action_rule',
        'base_iban',
        'base_import',
        'base_setup',
        'base_vat',
        'bus',
        'business_2_business',
        'business_2_business_need_sync',
        'business_2_business_product',
        'business_2_business_shipmentinfo',
        'currency_rate_live',
        'decimal_precision',
        'delivery',
        'document',
        'dropshipment_address',
        'erpopen_magento_odoo',
        'fetchmail',
        'grid',
        'l10n_nl',
        'l10n_nl_reports',
        'mail_push',
        'mrp_account',
        'need_sync_base',
        'need_sync_product',
        'partner_street_number',
        'payment',
        'payment_transfer',
        'portal',
        'portal_sale',
        'portal_stock',
        'procurement',
        'procurement_jit',
        'product',
        'purchase_mrp',
        'rating',
        'report',
        'resource',
        'sale_auto_invoice',
        'sale_crm',
        'sale_margin',
        'sale_mrp',
        'sale_order_dates',
        'sales_team',
        'sale_stock',
        'sanitairkamer_reports',
        'stock_dropshipping',
        'utm',
        'web',
        'web_calendar',
        'web_diagram',
        'web_editor',
        'web_enterprise',
        'web_gantt',
        'web_kanban',
        'web_kanban_gauge',
        'web_m2x_options',
        'web_mobile',
        'web_planner',
        'web_settings_dashboard',
        'website_enterprise',
        'website_form',
        'website_mail',
        'website_payment',
        'website_portal',
        'website_portal_sale',
        'website_sale_stock',
        'website_theme_install',
        'web_tour',
        'calendar',
        'theme_bootswatch',
    ],
    'data': [


    ],
    #'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
}
