{
    'name': 'Odoo Magento Connector',
    'version': '2.3',
    'category': 'all',
    'description': 'Magento odoo connector allows you to synchronize all the data on your magento ecommerce with odoo management. And it possible to import, export and update all your data.',
    'summary': 'Magento odoo connector. Import customers, quotations, sales orders, products, images and stock quantity. Update all your information. Export new contacts and products directly to your Magento Ecommerce. It synchronizes in real time and automatically all the data.',
    'author': 'Thom Peele - ERP|OPEN',
    'website': 'erpopen.nl',
    'support': 'info@erpopen.nl',
    'depends': [
        'base',
        'product',
        'sale',
        'stock',
        'delivery',
        'account_accountant',
        'purchase',
        'website_sale'
    ],
    'data': [
        'views/magento.xml',
        'views/magento_error_log.xml',
        'views/magento_odoo.xml',
        'views/product_product.xml',
        'views/import_widget.xml',
        'views/account_journal.xml',
        'views/delivery_carrier.xml',
        'views/sale_order.xml',
        'security/ir.model.access.csv',
        'data/error_log_cron.xml',
    ],
    'qweb': [
        'static/src/xml/multiwidget_template.xml',
    ],
    'installable': True,
    'auto_install': False,
    'images': ['images/icon.png'],
}
