SELECT "magento_settings"."magento_sale_order_auto_invoice" as
 "magento_sale_order_auto_invoice","magento_settings"."import_sales_orders_interval_units" as
 "import_sales_orders_interval_units","magento_settings"."import_attributes_interval_units" as
 "import_attributes_interval_units","magento_settings"."id" as
 "id","magento_settings"."import_attributes_interval_time" as
 "import_attributes_interval_time","magento_settings"."magento_sale_order_to" as
 "magento_sale_order_to","magento_settings"."magento_sale_order_from" as
 "magento_sale_order_from","magento_settings"."import_products_interval_time" as
 "import_products_interval_time","magento_settings"."magento_sale_order_prefix" as
 "magento_sale_order_prefix","magento_settings"."magento_currency_id" as
 "magento_currency_id","magento_settings"."write_date" as
 "write_date","magento_settings"."create_date" as
 "create_date","magento_settings"."import_categories_interval_units" as
 "import_categories_interval_units","magento_settings"."password" as
 "password","magento_settings"."magento_sale_order_from_ecommerce" as
 "magento_sale_order_from_ecommerce","magento_settings"."import_products_stock_interval_time" as
 "import_products_stock_interval_time","magento_settings"."import_customers_interval_units" as
 "import_customers_interval_units","magento_settings"."magento_journal_id" as
 "magento_journal_id","magento_settings"."enable_syncing_to_magento" as
 "enable_syncing_to_magento","magento_settings"."import_sales_orders_interval_time" as
 "import_sales_orders_interval_time","magento_settings"."import_products_interval_units" as
 "import_products_interval_units","magento_settings"."url" as
 "url","magento_settings"."magento_sale_journal_id" as
 "magento_sale_journal_id","magento_settings"."import_customers_interval_time" as
 "import_customers_interval_time","magento_settings"."magento_time_zone_adjustment" as
 "magento_time_zone_adjustment","magento_settings"."magento_account_id" as
 "magento_account_id","magento_settings"."incremental_imports" as
 "incremental_imports","magento_settings"."magento_sale_order_status" as
 "magento_sale_order_status","magento_settings"."import_products_stock_interval_units" as
 "import_products_stock_interval_units","magento_settings"."username" as
 "username","magento_settings"."magento_customer_email" as
 "magento_customer_email","magento_settings"."create_uid" as
 "create_uid","magento_settings"."import_categories_interval_time" as
 "import_categories_interval_time","magento_settings"."magento_product_simple_product" as
 "magento_product_simple_product","magento_settings"."magento_company_id" as
 "magento_company_id","magento_settings"."magento_invoice_prefix" as
 "magento_invoice_prefix","magento_settings"."write_uid" as
 "write_uid" FROM "magento_settings" WHERE "magento_settings".id IN (1)  ORDER BY "magento_settings"."id"

